# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'localize_main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 1163)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.toolContainer = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolContainer.sizePolicy().hasHeightForWidth())
        self.toolContainer.setSizePolicy(sizePolicy)
        self.toolContainer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolContainer.setObjectName("toolContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.toolContainer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.diodeSelectionTools = QtWidgets.QGroupBox(self.toolContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diodeSelectionTools.sizePolicy().hasHeightForWidth())
        self.diodeSelectionTools.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.diodeSelectionTools.setFont(font)
        self.diodeSelectionTools.setObjectName("diodeSelectionTools")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.diodeSelectionTools)
        self.horizontalLayout_3.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.diode1_selection = QtWidgets.QComboBox(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.diode1_selection.setFont(font)
        self.diode1_selection.setObjectName("diode1_selection")
        self.gridLayout_8.addWidget(self.diode1_selection, 0, 1, 1, 1)
        self.diode_orientation = QtWidgets.QDoubleSpinBox(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.diode_orientation.setFont(font)
        self.diode_orientation.setMinimum(-360.0)
        self.diode_orientation.setMaximum(360.0)
        self.diode_orientation.setObjectName("diode_orientation")
        self.gridLayout_8.addWidget(self.diode_orientation, 4, 1, 1, 1)
        self.diode2_selection = QtWidgets.QComboBox(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.diode2_selection.setFont(font)
        self.diode2_selection.setObjectName("diode2_selection")
        self.gridLayout_8.addWidget(self.diode2_selection, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 2, 0, 1, 1)
        self.diode1_validity = QtWidgets.QLabel(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.diode1_validity.setFont(font)
        self.diode1_validity.setText("")
        self.diode1_validity.setObjectName("diode1_validity")
        self.gridLayout_8.addWidget(self.diode1_validity, 0, 2, 1, 1)
        self.diode2_validity = QtWidgets.QLabel(self.diodeSelectionTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.diode2_validity.setFont(font)
        self.diode2_validity.setText("")
        self.diode2_validity.setObjectName("diode2_validity")
        self.gridLayout_8.addWidget(self.diode2_validity, 2, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_8)
        self.diode_plot = DiodeWidget(self.diodeSelectionTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.diode_plot.sizePolicy().hasHeightForWidth())
        self.diode_plot.setSizePolicy(sizePolicy)
        self.diode_plot.setMinimumSize(QtCore.QSize(75, 75))
        self.diode_plot.setAutoFillBackground(True)
        self.diode_plot.setObjectName("diode_plot")
        self.horizontalLayout_3.addWidget(self.diode_plot)
        self.verticalLayout.addWidget(self.diodeSelectionTools)
        self.regionsTools = QtWidgets.QGroupBox(self.toolContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regionsTools.sizePolicy().hasHeightForWidth())
        self.regionsTools.setSizePolicy(sizePolicy)
        self.regionsTools.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.regionsTools.setFont(font)
        self.regionsTools.setCheckable(True)
        self.regionsTools.setObjectName("regionsTools")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.regionsTools)
        self.gridLayout_5.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.regions = QtWidgets.QListWidget(self.regionsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.regions.sizePolicy().hasHeightForWidth())
        self.regions.setSizePolicy(sizePolicy)
        self.regions.setMinimumSize(QtCore.QSize(0, 0))
        self.regions.setMaximumSize(QtCore.QSize(150, 110))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.regions.setFont(font)
        self.regions.setObjectName("regions")
        self.gridLayout_5.addWidget(self.regions, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.regionsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.add_include_region = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_include_region.sizePolicy().hasHeightForWidth())
        self.add_include_region.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_include_region.setFont(font)
        self.add_include_region.setObjectName("add_include_region")
        self.verticalLayout_3.addWidget(self.add_include_region)
        self.add_exclude_region = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_exclude_region.sizePolicy().hasHeightForWidth())
        self.add_exclude_region.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.add_exclude_region.setFont(font)
        self.add_exclude_region.setObjectName("add_exclude_region")
        self.verticalLayout_3.addWidget(self.add_exclude_region)
        self.remove_region = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remove_region.sizePolicy().hasHeightForWidth())
        self.remove_region.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.remove_region.setFont(font)
        self.remove_region.setObjectName("remove_region")
        self.verticalLayout_3.addWidget(self.remove_region)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_5.addWidget(self.frame, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.regionsTools)
        self.removeJumpsTools = QtWidgets.QGroupBox(self.toolContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeJumpsTools.sizePolicy().hasHeightForWidth())
        self.removeJumpsTools.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.removeJumpsTools.setFont(font)
        self.removeJumpsTools.setAutoFillBackground(True)
        self.removeJumpsTools.setStyleSheet("")
        self.removeJumpsTools.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.removeJumpsTools.setFlat(False)
        self.removeJumpsTools.setCheckable(True)
        self.removeJumpsTools.setObjectName("removeJumpsTools")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.removeJumpsTools)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.removeJumpsTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.jumpsize = QtWidgets.QSpinBox(self.removeJumpsTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.jumpsize.setFont(font)
        self.jumpsize.setSpecialValueText("")
        self.jumpsize.setObjectName("jumpsize")
        self.horizontalLayout.addWidget(self.jumpsize)
        self.label_2 = QtWidgets.QLabel(self.removeJumpsTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.jumpduration = QtWidgets.QDoubleSpinBox(self.removeJumpsTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.jumpduration.setFont(font)
        self.jumpduration.setObjectName("jumpduration")
        self.horizontalLayout.addWidget(self.jumpduration)
        self.verticalLayout.addWidget(self.removeJumpsTools)
        self.smallGapInterpolationTools = QtWidgets.QGroupBox(self.toolContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.smallGapInterpolationTools.sizePolicy().hasHeightForWidth())
        self.smallGapInterpolationTools.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.smallGapInterpolationTools.setFont(font)
        self.smallGapInterpolationTools.setCheckable(True)
        self.smallGapInterpolationTools.setObjectName("smallGapInterpolationTools")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.smallGapInterpolationTools)
        self.horizontalLayout_9.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.smallGapInterpolationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.small_gapsize_interpolation = QtWidgets.QDoubleSpinBox(self.smallGapInterpolationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.small_gapsize_interpolation.setFont(font)
        self.small_gapsize_interpolation.setObjectName("small_gapsize_interpolation")
        self.horizontalLayout_9.addWidget(self.small_gapsize_interpolation)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.smallGapInterpolationTools)
        self.correctDiodeDistanceTools = QtWidgets.QGroupBox(self.toolContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.correctDiodeDistanceTools.sizePolicy().hasHeightForWidth())
        self.correctDiodeDistanceTools.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.correctDiodeDistanceTools.setFont(font)
        self.correctDiodeDistanceTools.setCheckable(True)
        self.correctDiodeDistanceTools.setObjectName("correctDiodeDistanceTools")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.correctDiodeDistanceTools)
        self.horizontalLayout_6.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.correctDiodeDistanceTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.diode_distance_threshold = QtWidgets.QDoubleSpinBox(self.correctDiodeDistanceTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.diode_distance_threshold.setFont(font)
        self.diode_distance_threshold.setObjectName("diode_distance_threshold")
        self.horizontalLayout_6.addWidget(self.diode_distance_threshold)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.correctDiodeDistanceTools)
        self.missingDiodeInterpolationTools = QtWidgets.QGroupBox(self.toolContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.missingDiodeInterpolationTools.sizePolicy().hasHeightForWidth())
        self.missingDiodeInterpolationTools.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.missingDiodeInterpolationTools.setFont(font)
        self.missingDiodeInterpolationTools.setCheckable(True)
        self.missingDiodeInterpolationTools.setObjectName("missingDiodeInterpolationTools")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.missingDiodeInterpolationTools)
        self.gridLayout_3.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.missingdiode_gapsize_interpolation = QtWidgets.QDoubleSpinBox(self.missingDiodeInterpolationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.missingdiode_gapsize_interpolation.setFont(font)
        self.missingdiode_gapsize_interpolation.setObjectName("missingdiode_gapsize_interpolation")
        self.gridLayout_3.addWidget(self.missingdiode_gapsize_interpolation, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.missingDiodeInterpolationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.missingDiodeInterpolationTools)
        self.finalGapInterpolationTools = QtWidgets.QGroupBox(self.toolContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finalGapInterpolationTools.sizePolicy().hasHeightForWidth())
        self.finalGapInterpolationTools.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.finalGapInterpolationTools.setFont(font)
        self.finalGapInterpolationTools.setCheckable(True)
        self.finalGapInterpolationTools.setObjectName("finalGapInterpolationTools")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.finalGapInterpolationTools)
        self.gridLayout_4.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.final_gapsize_interpolation = QtWidgets.QDoubleSpinBox(self.finalGapInterpolationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.final_gapsize_interpolation.setFont(font)
        self.final_gapsize_interpolation.setObjectName("final_gapsize_interpolation")
        self.gridLayout_4.addWidget(self.final_gapsize_interpolation, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.finalGapInterpolationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.finalGapInterpolationTools)
        self.behaviorEstimationTools = QtWidgets.QGroupBox(self.toolContainer)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.behaviorEstimationTools.setFont(font)
        self.behaviorEstimationTools.setObjectName("behaviorEstimationTools")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.behaviorEstimationTools)
        self.gridLayout_6.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.behaviorEstimationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.vel_smooth = QtWidgets.QDoubleSpinBox(self.behaviorEstimationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vel_smooth.setFont(font)
        self.vel_smooth.setObjectName("vel_smooth")
        self.horizontalLayout_11.addWidget(self.vel_smooth)
        self.gridLayout_6.addLayout(self.horizontalLayout_11, 0, 1, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.behaviorEstimationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_13.addWidget(self.label_9)
        self.hd_smooth = QtWidgets.QDoubleSpinBox(self.behaviorEstimationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.hd_smooth.setFont(font)
        self.hd_smooth.setObjectName("hd_smooth")
        self.horizontalLayout_13.addWidget(self.hd_smooth)
        self.gridLayout_6.addLayout(self.horizontalLayout_13, 2, 1, 1, 1)
        self.robust_position = QtWidgets.QCheckBox(self.behaviorEstimationTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.robust_position.sizePolicy().hasHeightForWidth())
        self.robust_position.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.robust_position.setFont(font)
        self.robust_position.setObjectName("robust_position")
        self.gridLayout_6.addWidget(self.robust_position, 0, 0, 1, 1)
        self.valid_position = QtWidgets.QLabel(self.behaviorEstimationTools)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.valid_position.setFont(font)
        self.valid_position.setText("")
        self.valid_position.setAlignment(QtCore.Qt.AlignCenter)
        self.valid_position.setObjectName("valid_position")
        self.gridLayout_6.addWidget(self.valid_position, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.behaviorEstimationTools)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.reset_button = QtWidgets.QPushButton(self.toolContainer)
        self.reset_button.setObjectName("reset_button")
        self.horizontalLayout_2.addWidget(self.reset_button)
        self.save_button = QtWidgets.QPushButton(self.toolContainer)
        self.save_button.setObjectName("save_button")
        self.horizontalLayout_2.addWidget(self.save_button)
        self.close_button = QtWidgets.QPushButton(self.toolContainer)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_7.addWidget(self.toolContainer, 3, 1, 1, 1)
        self.epochSelector = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.epochSelector.sizePolicy().hasHeightForWidth())
        self.epochSelector.setSizePolicy(sizePolicy)
        self.epochSelector.setMinimumSize(QtCore.QSize(0, 0))
        self.epochSelector.setObjectName("epochSelector")
        self.gridLayout_7.addWidget(self.epochSelector, 2, 1, 1, 1)
        self.figureContainer = QtWidgets.QVBoxLayout()
        self.figureContainer.setObjectName("figureContainer")
        self.gridLayout_7.addLayout(self.figureContainer, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.subjectSelectorButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subjectSelectorButton.sizePolicy().hasHeightForWidth())
        self.subjectSelectorButton.setSizePolicy(sizePolicy)
        self.subjectSelectorButton.setObjectName("subjectSelectorButton")
        self.horizontalLayout_4.addWidget(self.subjectSelectorButton)
        self.sessionSelector = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sessionSelector.sizePolicy().hasHeightForWidth())
        self.sessionSelector.setSizePolicy(sizePolicy)
        self.sessionSelector.setObjectName("sessionSelector")
        self.horizontalLayout_4.addWidget(self.sessionSelector)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1080, 30))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        self.epochSelector.currentIndexChanged['QString'].connect(MainWindow.epoch_selection_changed)
        self.robust_position.toggled['bool'].connect(MainWindow.robust_position_changed)
        self.regionsTools.toggled['bool'].connect(MainWindow.enable_regions)
        self.removeJumpsTools.toggled['bool'].connect(MainWindow.enable_removejumps)
        self.smallGapInterpolationTools.toggled['bool'].connect(MainWindow.enable_smallgapinterpolation)
        self.correctDiodeDistanceTools.toggled['bool'].connect(MainWindow.enable_correct_diode_distance)
        self.missingDiodeInterpolationTools.toggled['bool'].connect(MainWindow.enable_missingdiode_interpolation)
        self.finalGapInterpolationTools.toggled['bool'].connect(MainWindow.enable_finalgapinterpolation)
        self.diode1_selection.currentIndexChanged['QString'].connect(MainWindow.diode_selection_changed)
        self.diode2_selection.currentIndexChanged['QString'].connect(MainWindow.diode_selection_changed)
        self.diode_orientation.valueChanged['double'].connect(MainWindow.diode_orientation_changed)
        self.add_include_region.clicked.connect(MainWindow.add_include_region)
        self.add_exclude_region.clicked.connect(MainWindow.add_exclude_region)
        self.remove_region.clicked.connect(MainWindow.remove_region)
        self.jumpsize.valueChanged['int'].connect(MainWindow.jumpsize_changed)
        self.jumpduration.valueChanged['double'].connect(MainWindow.jumpduration_changed)
        self.small_gapsize_interpolation.valueChanged['double'].connect(MainWindow.small_gapsize_interpolation_changed)
        self.diode_distance_threshold.valueChanged['double'].connect(MainWindow.diode_distance_threshold_changed)
        self.final_gapsize_interpolation.valueChanged['double'].connect(MainWindow.final_gapsize_interpolation_changed)
        self.missingdiode_gapsize_interpolation.valueChanged['double'].connect(MainWindow.missingdiode_gapsize_interpolation_changed)
        self.vel_smooth.valueChanged['double'].connect(MainWindow.vel_smooth_changed)
        self.hd_smooth.valueChanged['double'].connect(MainWindow.hd_smooth_changed)
        self.close_button.clicked.connect(MainWindow.close_button_clicked)
        self.save_button.clicked.connect(MainWindow.save_button_clicked)
        self.reset_button.clicked.connect(MainWindow.reset_button_clicked)
        self.subjectSelectorButton.clicked.connect(MainWindow.subject_change_request)
        self.sessionSelector.currentIndexChanged['QString'].connect(MainWindow.session_changed)
        self.regions.currentRowChanged['int'].connect(MainWindow.region_selection_changed)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Localize"))
        self.diodeSelectionTools.setToolTip(_translate("MainWindow", "Select which diodes need to be processed"))
        self.diodeSelectionTools.setTitle(_translate("MainWindow", "diode selection"))
        self.label_12.setText(_translate("MainWindow", "orientation"))
        self.label_10.setText(_translate("MainWindow", "diode 1"))
        self.label_11.setText(_translate("MainWindow", "diode 2"))
        self.regionsTools.setToolTip(_translate("MainWindow", "Set inclusive and exclusive regions"))
        self.regionsTools.setTitle(_translate("MainWindow", "include/exclude regions"))
        self.regions.setToolTip(_translate("MainWindow", "List of regions"))
        self.add_include_region.setToolTip(_translate("MainWindow", "Add new inclusive region"))
        self.add_include_region.setText(_translate("MainWindow", "include region"))
        self.add_exclude_region.setToolTip(_translate("MainWindow", "Add new exclusive region"))
        self.add_exclude_region.setText(_translate("MainWindow", "exclude region"))
        self.remove_region.setToolTip(_translate("MainWindow", "Remove selected regions"))
        self.remove_region.setText(_translate("MainWindow", "remove region"))
        self.removeJumpsTools.setToolTip(_translate("MainWindow", "Remove large spatial jumps"))
        self.removeJumpsTools.setTitle(_translate("MainWindow", "remove jumps"))
        self.label.setToolTip(_translate("MainWindow", "Jump size in pixels"))
        self.label.setText(_translate("MainWindow", "jump size (px)"))
        self.jumpsize.setToolTip(_translate("MainWindow", "Jump size in pixels"))
        self.label_2.setToolTip(_translate("MainWindow", "Maximum jump duration in seconds"))
        self.label_2.setText(_translate("MainWindow", "duration (s)"))
        self.jumpduration.setToolTip(_translate("MainWindow", "Maximum jump duration in seconds"))
        self.smallGapInterpolationTools.setToolTip(_translate("MainWindow", "Interpolation of short duration gaps"))
        self.smallGapInterpolationTools.setTitle(_translate("MainWindow", "small gap interpolation"))
        self.label_3.setToolTip(_translate("MainWindow", "Maximum gap duration that will be interpolated"))
        self.label_3.setText(_translate("MainWindow", "max gap (s)"))
        self.small_gapsize_interpolation.setToolTip(_translate("MainWindow", "Maximum gap duration that will be interpolated"))
        self.correctDiodeDistanceTools.setToolTip(_translate("MainWindow", "Remove sample where diode distance is either very small or very large"))
        self.correctDiodeDistanceTools.setTitle(_translate("MainWindow", "correct diode distance"))
        self.label_4.setToolTip(_translate("MainWindow", "Diode distance threshold (multiplication factor for inter-quartile range)"))
        self.label_4.setText(_translate("MainWindow", "threshold"))
        self.diode_distance_threshold.setToolTip(_translate("MainWindow", "Diode distance threshold (multiplication factor for inter-quartile range)"))
        self.missingDiodeInterpolationTools.setToolTip(_translate("MainWindow", "Interpolate gaps where only one diode is available"))
        self.missingDiodeInterpolationTools.setTitle(_translate("MainWindow", "missing diode interpolation"))
        self.missingdiode_gapsize_interpolation.setToolTip(_translate("MainWindow", "Maximum gap duration that will be interpolated"))
        self.label_5.setToolTip(_translate("MainWindow", "Maximum gap duration that will be interpolated"))
        self.label_5.setText(_translate("MainWindow", "max gap (s)"))
        self.finalGapInterpolationTools.setToolTip(_translate("MainWindow", "Final large gap interpolation"))
        self.finalGapInterpolationTools.setTitle(_translate("MainWindow", "final gap interpolation"))
        self.final_gapsize_interpolation.setToolTip(_translate("MainWindow", "Maximum gap duration that will be interpolated"))
        self.label_6.setToolTip(_translate("MainWindow", "Maximum gap duration that will be interpolated"))
        self.label_6.setText(_translate("MainWindow", "max gap (s)"))
        self.behaviorEstimationTools.setToolTip(_translate("MainWindow", "Parameters for position, head direction and velocity estimation"))
        self.behaviorEstimationTools.setTitle(_translate("MainWindow", "behavior estimation"))
        self.label_7.setToolTip(_translate("MainWindow", "Smoothing bandwidth for velocity"))
        self.label_7.setText(_translate("MainWindow", "vel smooth(s)"))
        self.vel_smooth.setToolTip(_translate("MainWindow", "Smoothing bandwidth for velocity"))
        self.label_9.setToolTip(_translate("MainWindow", "Smoothing bandwidth for head direction"))
        self.label_9.setText(_translate("MainWindow", "hd smooth (s)"))
        self.hd_smooth.setToolTip(_translate("MainWindow", "Smoothing bandwidth for head direction"))
        self.robust_position.setToolTip(_translate("MainWindow", "Enable estimation of position even if one diode is missing"))
        self.robust_position.setText(_translate("MainWindow", "robust position"))
        self.reset_button.setToolTip(_translate("MainWindow", "Reset parameters to saved values"))
        self.reset_button.setText(_translate("MainWindow", "Reset"))
        self.save_button.setToolTip(_translate("MainWindow", "Save current parameters"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.close_button.setToolTip(_translate("MainWindow", "Close application"))
        self.close_button.setText(_translate("MainWindow", "Close"))
        self.epochSelector.setToolTip(_translate("MainWindow", "Select epoch"))
        self.subjectSelectorButton.setText(_translate("MainWindow", "Subject Folder"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))

from fklab.ui.pyqt.widgets import DiodeWidget
