# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'amaze_main2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(940, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.position_data_source = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.position_data_source.sizePolicy().hasHeightForWidth())
        self.position_data_source.setSizePolicy(sizePolicy)
        self.position_data_source.setText(_fromUtf8(""))
        self.position_data_source.setObjectName(_fromUtf8("position_data_source"))
        self.gridLayout_2.addWidget(self.position_data_source, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.frame_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.video_image_source = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.video_image_source.sizePolicy().hasHeightForWidth())
        self.video_image_source.setSizePolicy(sizePolicy)
        self.video_image_source.setText(_fromUtf8(""))
        self.video_image_source.setObjectName(_fromUtf8("video_image_source"))
        self.gridLayout_2.addWidget(self.video_image_source, 2, 1, 1, 1)
        self.env_description_file = QtGui.QLabel(self.frame_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.env_description_file.sizePolicy().hasHeightForWidth())
        self.env_description_file.setSizePolicy(sizePolicy)
        self.env_description_file.setText(_fromUtf8(""))
        self.env_description_file.setObjectName(_fromUtf8("env_description_file"))
        self.gridLayout_2.addWidget(self.env_description_file, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.Canvas = GraphicsCanvas(self.centralwidget)
        self.Canvas.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Canvas.sizePolicy().hasHeightForWidth())
        self.Canvas.setSizePolicy(sizePolicy)
        self.Canvas.setObjectName(_fromUtf8("Canvas"))
        self.horizontalLayout_6.addWidget(self.Canvas)
        self.ToolboxFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ToolboxFrame.sizePolicy().hasHeightForWidth())
        self.ToolboxFrame.setSizePolicy(sizePolicy)
        self.ToolboxFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ToolboxFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.ToolboxFrame.setObjectName(_fromUtf8("ToolboxFrame"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.ToolboxFrame)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.ToolboxFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.EnvironmentList = QtGui.QListWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EnvironmentList.sizePolicy().hasHeightForWidth())
        self.EnvironmentList.setSizePolicy(sizePolicy)
        self.EnvironmentList.setMinimumSize(QtCore.QSize(100, 50))
        self.EnvironmentList.setMaximumSize(QtCore.QSize(500, 130))
        self.EnvironmentList.setObjectName(_fromUtf8("EnvironmentList"))
        self.horizontalLayout_3.addWidget(self.EnvironmentList)
        self.frame = QtGui.QFrame(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.AddEnvironment = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddEnvironment.sizePolicy().hasHeightForWidth())
        self.AddEnvironment.setSizePolicy(sizePolicy)
        self.AddEnvironment.setObjectName(_fromUtf8("AddEnvironment"))
        self.verticalLayout_2.addWidget(self.AddEnvironment)
        self.RemoveEnvironment = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveEnvironment.sizePolicy().hasHeightForWidth())
        self.RemoveEnvironment.setSizePolicy(sizePolicy)
        self.RemoveEnvironment.setObjectName(_fromUtf8("RemoveEnvironment"))
        self.verticalLayout_2.addWidget(self.RemoveEnvironment)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.ShapeFrame = QtGui.QGroupBox(self.ToolboxFrame)
        self.ShapeFrame.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShapeFrame.sizePolicy().hasHeightForWidth())
        self.ShapeFrame.setSizePolicy(sizePolicy)
        self.ShapeFrame.setObjectName(_fromUtf8("ShapeFrame"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.ShapeFrame)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.ShapeTable = QtGui.QTableWidget(self.ShapeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShapeTable.sizePolicy().hasHeightForWidth())
        self.ShapeTable.setSizePolicy(sizePolicy)
        self.ShapeTable.setMinimumSize(QtCore.QSize(200, 0))
        self.ShapeTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ShapeTable.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.ShapeTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.ShapeTable.setShowGrid(False)
        self.ShapeTable.setObjectName(_fromUtf8("ShapeTable"))
        self.ShapeTable.setColumnCount(2)
        self.ShapeTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.ShapeTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.ShapeTable.setHorizontalHeaderItem(1, item)
        self.ShapeTable.horizontalHeader().setDefaultSectionSize(100)
        self.ShapeTable.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.ShapeTable)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.RemoveShapes = QtGui.QPushButton(self.ShapeFrame)
        self.RemoveShapes.setObjectName(_fromUtf8("RemoveShapes"))
        self.horizontalLayout.addWidget(self.RemoveShapes)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.frame_2 = QtGui.QFrame(self.ShapeFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout = QtGui.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.RectTrackChooser = ScrollStackWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectTrackChooser.sizePolicy().hasHeightForWidth())
        self.RectTrackChooser.setSizePolicy(sizePolicy)
        self.RectTrackChooser.setMinimumSize(QtCore.QSize(0, 0))
        self.RectTrackChooser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RectTrackChooser.setFrameShape(QtGui.QFrame.NoFrame)
        self.RectTrackChooser.setFrameShadow(QtGui.QFrame.Plain)
        self.RectTrackChooser.setLineWidth(1)
        self.RectTrackChooser.setObjectName(_fromUtf8("RectTrackChooser"))
        self.RectTrack1 = QtGui.QWidget()
        self.RectTrack1.setMinimumSize(QtCore.QSize(46, 34))
        self.RectTrack1.setMaximumSize(QtCore.QSize(46, 34))
        self.RectTrack1.setObjectName(_fromUtf8("RectTrack1"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.RectTrack1)
        self.horizontalLayout_9.setMargin(0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.RectTrack1Button = QtGui.QPushButton(self.RectTrack1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectTrack1Button.sizePolicy().hasHeightForWidth())
        self.RectTrack1Button.setSizePolicy(sizePolicy)
        self.RectTrack1Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectTrack1Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectTrack1Button.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track3_v2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectTrack1Button.setIcon(icon1)
        self.RectTrack1Button.setIconSize(QtCore.QSize(24, 24))
        self.RectTrack1Button.setObjectName(_fromUtf8("RectTrack1Button"))
        self.horizontalLayout_9.addWidget(self.RectTrack1Button)
        self.RectTrackChooser.addWidget(self.RectTrack1)
        self.RectTrack2 = QtGui.QWidget()
        self.RectTrack2.setMinimumSize(QtCore.QSize(46, 34))
        self.RectTrack2.setMaximumSize(QtCore.QSize(46, 34))
        self.RectTrack2.setObjectName(_fromUtf8("RectTrack2"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.RectTrack2)
        self.horizontalLayout_10.setMargin(0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.RectTrack2Button = QtGui.QPushButton(self.RectTrack2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectTrack2Button.sizePolicy().hasHeightForWidth())
        self.RectTrack2Button.setSizePolicy(sizePolicy)
        self.RectTrack2Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectTrack2Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectTrack2Button.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track3_v3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectTrack2Button.setIcon(icon2)
        self.RectTrack2Button.setIconSize(QtCore.QSize(24, 24))
        self.RectTrack2Button.setObjectName(_fromUtf8("RectTrack2Button"))
        self.horizontalLayout_10.addWidget(self.RectTrack2Button)
        self.RectTrackChooser.addWidget(self.RectTrack2)
        self.RectTrack3 = QtGui.QWidget()
        self.RectTrack3.setMinimumSize(QtCore.QSize(46, 34))
        self.RectTrack3.setMaximumSize(QtCore.QSize(46, 34))
        self.RectTrack3.setObjectName(_fromUtf8("RectTrack3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.RectTrack3)
        self.horizontalLayout_11.setMargin(0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.RectTrack3Button = QtGui.QPushButton(self.RectTrack3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectTrack3Button.sizePolicy().hasHeightForWidth())
        self.RectTrack3Button.setSizePolicy(sizePolicy)
        self.RectTrack3Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectTrack3Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectTrack3Button.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track3_v4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectTrack3Button.setIcon(icon3)
        self.RectTrack3Button.setIconSize(QtCore.QSize(24, 24))
        self.RectTrack3Button.setObjectName(_fromUtf8("RectTrack3Button"))
        self.horizontalLayout_11.addWidget(self.RectTrack3Button)
        self.RectTrackChooser.addWidget(self.RectTrack3)
        self.gridLayout.addWidget(self.RectTrackChooser, 0, 3, 1, 1)
        self.LinearTrackButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LinearTrackButton.sizePolicy().hasHeightForWidth())
        self.LinearTrackButton.setSizePolicy(sizePolicy)
        self.LinearTrackButton.setText(_fromUtf8(""))
        self.LinearTrackButton.setIcon(icon)
        self.LinearTrackButton.setIconSize(QtCore.QSize(24, 24))
        self.LinearTrackButton.setAutoDefault(False)
        self.LinearTrackButton.setDefault(False)
        self.LinearTrackButton.setFlat(False)
        self.LinearTrackButton.setObjectName(_fromUtf8("LinearTrackButton"))
        self.gridLayout.addWidget(self.LinearTrackButton, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.CircTrackChooser = ScrollStackWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircTrackChooser.sizePolicy().hasHeightForWidth())
        self.CircTrackChooser.setSizePolicy(sizePolicy)
        self.CircTrackChooser.setMinimumSize(QtCore.QSize(0, 0))
        self.CircTrackChooser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CircTrackChooser.setFrameShape(QtGui.QFrame.NoFrame)
        self.CircTrackChooser.setFrameShadow(QtGui.QFrame.Plain)
        self.CircTrackChooser.setLineWidth(1)
        self.CircTrackChooser.setObjectName(_fromUtf8("CircTrackChooser"))
        self.CircTrack1 = QtGui.QWidget()
        self.CircTrack1.setMinimumSize(QtCore.QSize(46, 34))
        self.CircTrack1.setMaximumSize(QtCore.QSize(46, 34))
        self.CircTrack1.setObjectName(_fromUtf8("CircTrack1"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.CircTrack1)
        self.horizontalLayout_12.setMargin(0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.CircTrack1Button = QtGui.QPushButton(self.CircTrack1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircTrack1Button.sizePolicy().hasHeightForWidth())
        self.CircTrack1Button.setSizePolicy(sizePolicy)
        self.CircTrack1Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircTrack1Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircTrack1Button.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track2_v2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircTrack1Button.setIcon(icon4)
        self.CircTrack1Button.setIconSize(QtCore.QSize(24, 24))
        self.CircTrack1Button.setObjectName(_fromUtf8("CircTrack1Button"))
        self.horizontalLayout_12.addWidget(self.CircTrack1Button)
        self.CircTrackChooser.addWidget(self.CircTrack1)
        self.CircTrack2 = QtGui.QWidget()
        self.CircTrack2.setMinimumSize(QtCore.QSize(46, 34))
        self.CircTrack2.setMaximumSize(QtCore.QSize(46, 34))
        self.CircTrack2.setObjectName(_fromUtf8("CircTrack2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.CircTrack2)
        self.horizontalLayout_13.setMargin(0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.CircTrack2Button = QtGui.QPushButton(self.CircTrack2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircTrack2Button.sizePolicy().hasHeightForWidth())
        self.CircTrack2Button.setSizePolicy(sizePolicy)
        self.CircTrack2Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircTrack2Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircTrack2Button.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track2_v3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircTrack2Button.setIcon(icon5)
        self.CircTrack2Button.setIconSize(QtCore.QSize(24, 24))
        self.CircTrack2Button.setObjectName(_fromUtf8("CircTrack2Button"))
        self.horizontalLayout_13.addWidget(self.CircTrack2Button)
        self.CircTrackChooser.addWidget(self.CircTrack2)
        self.CircTrack3 = QtGui.QWidget()
        self.CircTrack3.setMinimumSize(QtCore.QSize(46, 34))
        self.CircTrack3.setMaximumSize(QtCore.QSize(46, 34))
        self.CircTrack3.setObjectName(_fromUtf8("CircTrack3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.CircTrack3)
        self.horizontalLayout_14.setMargin(0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.CircTrack3Button = QtGui.QPushButton(self.CircTrack3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircTrack3Button.sizePolicy().hasHeightForWidth())
        self.CircTrack3Button.setSizePolicy(sizePolicy)
        self.CircTrack3Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircTrack3Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircTrack3Button.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track2_v4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircTrack3Button.setIcon(icon6)
        self.CircTrack3Button.setIconSize(QtCore.QSize(24, 24))
        self.CircTrack3Button.setObjectName(_fromUtf8("CircTrack3Button"))
        self.horizontalLayout_14.addWidget(self.CircTrack3Button)
        self.CircTrackChooser.addWidget(self.CircTrack3)
        self.gridLayout.addWidget(self.CircTrackChooser, 0, 2, 1, 1)
        self.GraphTrackButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GraphTrackButton.sizePolicy().hasHeightForWidth())
        self.GraphTrackButton.setSizePolicy(sizePolicy)
        self.GraphTrackButton.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/track4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.GraphTrackButton.setIcon(icon7)
        self.GraphTrackButton.setIconSize(QtCore.QSize(24, 24))
        self.GraphTrackButton.setObjectName(_fromUtf8("GraphTrackButton"))
        self.gridLayout.addWidget(self.GraphTrackButton, 0, 4, 1, 1)
        self.PolygonFieldButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PolygonFieldButton.sizePolicy().hasHeightForWidth())
        self.PolygonFieldButton.setSizePolicy(sizePolicy)
        self.PolygonFieldButton.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/field3_v4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PolygonFieldButton.setIcon(icon8)
        self.PolygonFieldButton.setIconSize(QtCore.QSize(24, 24))
        self.PolygonFieldButton.setObjectName(_fromUtf8("PolygonFieldButton"))
        self.gridLayout.addWidget(self.PolygonFieldButton, 1, 1, 1, 1)
        self.PolygonObjectButton = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PolygonObjectButton.sizePolicy().hasHeightForWidth())
        self.PolygonObjectButton.setSizePolicy(sizePolicy)
        self.PolygonObjectButton.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/object3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PolygonObjectButton.setIcon(icon9)
        self.PolygonObjectButton.setIconSize(QtCore.QSize(24, 24))
        self.PolygonObjectButton.setObjectName(_fromUtf8("PolygonObjectButton"))
        self.gridLayout.addWidget(self.PolygonObjectButton, 2, 1, 1, 1)
        self.RectFieldChooser = ScrollStackWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectFieldChooser.sizePolicy().hasHeightForWidth())
        self.RectFieldChooser.setSizePolicy(sizePolicy)
        self.RectFieldChooser.setMinimumSize(QtCore.QSize(0, 0))
        self.RectFieldChooser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RectFieldChooser.setFrameShape(QtGui.QFrame.NoFrame)
        self.RectFieldChooser.setFrameShadow(QtGui.QFrame.Plain)
        self.RectFieldChooser.setLineWidth(1)
        self.RectFieldChooser.setObjectName(_fromUtf8("RectFieldChooser"))
        self.RectField1 = QtGui.QWidget()
        self.RectField1.setMinimumSize(QtCore.QSize(46, 34))
        self.RectField1.setMaximumSize(QtCore.QSize(46, 34))
        self.RectField1.setObjectName(_fromUtf8("RectField1"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout(self.RectField1)
        self.horizontalLayout_24.setMargin(0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.RectField1Button = QtGui.QPushButton(self.RectField1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectField1Button.sizePolicy().hasHeightForWidth())
        self.RectField1Button.setSizePolicy(sizePolicy)
        self.RectField1Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectField1Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectField1Button.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/field2_v2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectField1Button.setIcon(icon10)
        self.RectField1Button.setIconSize(QtCore.QSize(24, 24))
        self.RectField1Button.setObjectName(_fromUtf8("RectField1Button"))
        self.horizontalLayout_24.addWidget(self.RectField1Button)
        self.RectFieldChooser.addWidget(self.RectField1)
        self.RectField2 = QtGui.QWidget()
        self.RectField2.setMinimumSize(QtCore.QSize(46, 34))
        self.RectField2.setMaximumSize(QtCore.QSize(46, 34))
        self.RectField2.setObjectName(_fromUtf8("RectField2"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout(self.RectField2)
        self.horizontalLayout_25.setMargin(0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.RectField2Button = QtGui.QPushButton(self.RectField2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectField2Button.sizePolicy().hasHeightForWidth())
        self.RectField2Button.setSizePolicy(sizePolicy)
        self.RectField2Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectField2Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectField2Button.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/field2_v3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectField2Button.setIcon(icon11)
        self.RectField2Button.setIconSize(QtCore.QSize(24, 24))
        self.RectField2Button.setObjectName(_fromUtf8("RectField2Button"))
        self.horizontalLayout_25.addWidget(self.RectField2Button)
        self.RectFieldChooser.addWidget(self.RectField2)
        self.RectField3 = QtGui.QWidget()
        self.RectField3.setMinimumSize(QtCore.QSize(46, 34))
        self.RectField3.setMaximumSize(QtCore.QSize(46, 34))
        self.RectField3.setObjectName(_fromUtf8("RectField3"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout(self.RectField3)
        self.horizontalLayout_26.setMargin(0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.RectField3Button = QtGui.QPushButton(self.RectField3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectField3Button.sizePolicy().hasHeightForWidth())
        self.RectField3Button.setSizePolicy(sizePolicy)
        self.RectField3Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectField3Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectField3Button.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/field2_v4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectField3Button.setIcon(icon12)
        self.RectField3Button.setIconSize(QtCore.QSize(24, 24))
        self.RectField3Button.setObjectName(_fromUtf8("RectField3Button"))
        self.horizontalLayout_26.addWidget(self.RectField3Button)
        self.RectFieldChooser.addWidget(self.RectField3)
        self.gridLayout.addWidget(self.RectFieldChooser, 1, 3, 1, 1)
        self.RectObjectChooser = ScrollStackWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectObjectChooser.sizePolicy().hasHeightForWidth())
        self.RectObjectChooser.setSizePolicy(sizePolicy)
        self.RectObjectChooser.setMinimumSize(QtCore.QSize(0, 0))
        self.RectObjectChooser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.RectObjectChooser.setFrameShape(QtGui.QFrame.NoFrame)
        self.RectObjectChooser.setFrameShadow(QtGui.QFrame.Plain)
        self.RectObjectChooser.setLineWidth(1)
        self.RectObjectChooser.setObjectName(_fromUtf8("RectObjectChooser"))
        self.RectObject1 = QtGui.QWidget()
        self.RectObject1.setMinimumSize(QtCore.QSize(46, 34))
        self.RectObject1.setMaximumSize(QtCore.QSize(46, 34))
        self.RectObject1.setObjectName(_fromUtf8("RectObject1"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout(self.RectObject1)
        self.horizontalLayout_18.setMargin(0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.RectObject1Button = QtGui.QPushButton(self.RectObject1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectObject1Button.sizePolicy().hasHeightForWidth())
        self.RectObject1Button.setSizePolicy(sizePolicy)
        self.RectObject1Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectObject1Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectObject1Button.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/object2_v2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectObject1Button.setIcon(icon13)
        self.RectObject1Button.setIconSize(QtCore.QSize(24, 24))
        self.RectObject1Button.setObjectName(_fromUtf8("RectObject1Button"))
        self.horizontalLayout_18.addWidget(self.RectObject1Button)
        self.RectObjectChooser.addWidget(self.RectObject1)
        self.RectObject2 = QtGui.QWidget()
        self.RectObject2.setMinimumSize(QtCore.QSize(46, 34))
        self.RectObject2.setMaximumSize(QtCore.QSize(46, 34))
        self.RectObject2.setObjectName(_fromUtf8("RectObject2"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.RectObject2)
        self.horizontalLayout_19.setMargin(0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.RectObject2Button = QtGui.QPushButton(self.RectObject2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectObject2Button.sizePolicy().hasHeightForWidth())
        self.RectObject2Button.setSizePolicy(sizePolicy)
        self.RectObject2Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectObject2Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectObject2Button.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/object2_v3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectObject2Button.setIcon(icon14)
        self.RectObject2Button.setIconSize(QtCore.QSize(24, 24))
        self.RectObject2Button.setObjectName(_fromUtf8("RectObject2Button"))
        self.horizontalLayout_19.addWidget(self.RectObject2Button)
        self.RectObjectChooser.addWidget(self.RectObject2)
        self.RectObject3 = QtGui.QWidget()
        self.RectObject3.setMinimumSize(QtCore.QSize(46, 34))
        self.RectObject3.setMaximumSize(QtCore.QSize(46, 34))
        self.RectObject3.setObjectName(_fromUtf8("RectObject3"))
        self.horizontalLayout_20 = QtGui.QHBoxLayout(self.RectObject3)
        self.horizontalLayout_20.setMargin(0)
        self.horizontalLayout_20.setSpacing(0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.RectObject3Button = QtGui.QPushButton(self.RectObject3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RectObject3Button.sizePolicy().hasHeightForWidth())
        self.RectObject3Button.setSizePolicy(sizePolicy)
        self.RectObject3Button.setMinimumSize(QtCore.QSize(46, 34))
        self.RectObject3Button.setMaximumSize(QtCore.QSize(46, 34))
        self.RectObject3Button.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/object2_v4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RectObject3Button.setIcon(icon15)
        self.RectObject3Button.setIconSize(QtCore.QSize(24, 24))
        self.RectObject3Button.setObjectName(_fromUtf8("RectObject3Button"))
        self.horizontalLayout_20.addWidget(self.RectObject3Button)
        self.RectObjectChooser.addWidget(self.RectObject3)
        self.gridLayout.addWidget(self.RectObjectChooser, 2, 3, 1, 1)
        self.CircFieldChooser = ScrollStackWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircFieldChooser.sizePolicy().hasHeightForWidth())
        self.CircFieldChooser.setSizePolicy(sizePolicy)
        self.CircFieldChooser.setMinimumSize(QtCore.QSize(0, 0))
        self.CircFieldChooser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CircFieldChooser.setFrameShape(QtGui.QFrame.NoFrame)
        self.CircFieldChooser.setFrameShadow(QtGui.QFrame.Plain)
        self.CircFieldChooser.setLineWidth(1)
        self.CircFieldChooser.setObjectName(_fromUtf8("CircFieldChooser"))
        self.CircField1 = QtGui.QWidget()
        self.CircField1.setMinimumSize(QtCore.QSize(46, 34))
        self.CircField1.setMaximumSize(QtCore.QSize(46, 34))
        self.CircField1.setObjectName(_fromUtf8("CircField1"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout(self.CircField1)
        self.horizontalLayout_21.setMargin(0)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.CircField1Button = QtGui.QPushButton(self.CircField1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircField1Button.sizePolicy().hasHeightForWidth())
        self.CircField1Button.setSizePolicy(sizePolicy)
        self.CircField1Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircField1Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircField1Button.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/field1_v2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircField1Button.setIcon(icon16)
        self.CircField1Button.setIconSize(QtCore.QSize(24, 24))
        self.CircField1Button.setObjectName(_fromUtf8("CircField1Button"))
        self.horizontalLayout_21.addWidget(self.CircField1Button)
        self.CircFieldChooser.addWidget(self.CircField1)
        self.CircField2 = QtGui.QWidget()
        self.CircField2.setMinimumSize(QtCore.QSize(46, 34))
        self.CircField2.setMaximumSize(QtCore.QSize(46, 34))
        self.CircField2.setObjectName(_fromUtf8("CircField2"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout(self.CircField2)
        self.horizontalLayout_22.setMargin(0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.CircField2Button = QtGui.QPushButton(self.CircField2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircField2Button.sizePolicy().hasHeightForWidth())
        self.CircField2Button.setSizePolicy(sizePolicy)
        self.CircField2Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircField2Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircField2Button.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/field1_v3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircField2Button.setIcon(icon17)
        self.CircField2Button.setIconSize(QtCore.QSize(24, 24))
        self.CircField2Button.setObjectName(_fromUtf8("CircField2Button"))
        self.horizontalLayout_22.addWidget(self.CircField2Button)
        self.CircFieldChooser.addWidget(self.CircField2)
        self.CircField3 = QtGui.QWidget()
        self.CircField3.setMinimumSize(QtCore.QSize(46, 34))
        self.CircField3.setMaximumSize(QtCore.QSize(46, 34))
        self.CircField3.setObjectName(_fromUtf8("CircField3"))
        self.horizontalLayout_23 = QtGui.QHBoxLayout(self.CircField3)
        self.horizontalLayout_23.setMargin(0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.CircField3Button = QtGui.QPushButton(self.CircField3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircField3Button.sizePolicy().hasHeightForWidth())
        self.CircField3Button.setSizePolicy(sizePolicy)
        self.CircField3Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircField3Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircField3Button.setText(_fromUtf8(""))
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/field1_v4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircField3Button.setIcon(icon18)
        self.CircField3Button.setIconSize(QtCore.QSize(24, 24))
        self.CircField3Button.setObjectName(_fromUtf8("CircField3Button"))
        self.horizontalLayout_23.addWidget(self.CircField3Button)
        self.CircFieldChooser.addWidget(self.CircField3)
        self.gridLayout.addWidget(self.CircFieldChooser, 1, 2, 1, 1)
        self.CircObjectChooser = ScrollStackWidget(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircObjectChooser.sizePolicy().hasHeightForWidth())
        self.CircObjectChooser.setSizePolicy(sizePolicy)
        self.CircObjectChooser.setMinimumSize(QtCore.QSize(0, 0))
        self.CircObjectChooser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CircObjectChooser.setFrameShape(QtGui.QFrame.NoFrame)
        self.CircObjectChooser.setFrameShadow(QtGui.QFrame.Plain)
        self.CircObjectChooser.setLineWidth(1)
        self.CircObjectChooser.setObjectName(_fromUtf8("CircObjectChooser"))
        self.CircObject1 = QtGui.QWidget()
        self.CircObject1.setMinimumSize(QtCore.QSize(46, 34))
        self.CircObject1.setMaximumSize(QtCore.QSize(46, 34))
        self.CircObject1.setObjectName(_fromUtf8("CircObject1"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.CircObject1)
        self.horizontalLayout_15.setMargin(0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.CircObject1Button = QtGui.QPushButton(self.CircObject1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircObject1Button.sizePolicy().hasHeightForWidth())
        self.CircObject1Button.setSizePolicy(sizePolicy)
        self.CircObject1Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircObject1Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircObject1Button.setText(_fromUtf8(""))
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/object1_v2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircObject1Button.setIcon(icon19)
        self.CircObject1Button.setIconSize(QtCore.QSize(24, 24))
        self.CircObject1Button.setObjectName(_fromUtf8("CircObject1Button"))
        self.horizontalLayout_15.addWidget(self.CircObject1Button)
        self.CircObjectChooser.addWidget(self.CircObject1)
        self.CircObject2 = QtGui.QWidget()
        self.CircObject2.setMinimumSize(QtCore.QSize(46, 34))
        self.CircObject2.setMaximumSize(QtCore.QSize(46, 34))
        self.CircObject2.setObjectName(_fromUtf8("CircObject2"))
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.CircObject2)
        self.horizontalLayout_16.setMargin(0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.CircObject2Button = QtGui.QPushButton(self.CircObject2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircObject2Button.sizePolicy().hasHeightForWidth())
        self.CircObject2Button.setSizePolicy(sizePolicy)
        self.CircObject2Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircObject2Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircObject2Button.setText(_fromUtf8(""))
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/object1_v3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircObject2Button.setIcon(icon20)
        self.CircObject2Button.setIconSize(QtCore.QSize(24, 24))
        self.CircObject2Button.setObjectName(_fromUtf8("CircObject2Button"))
        self.horizontalLayout_16.addWidget(self.CircObject2Button)
        self.CircObjectChooser.addWidget(self.CircObject2)
        self.CircObject3 = QtGui.QWidget()
        self.CircObject3.setMinimumSize(QtCore.QSize(46, 34))
        self.CircObject3.setMaximumSize(QtCore.QSize(46, 34))
        self.CircObject3.setObjectName(_fromUtf8("CircObject3"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.CircObject3)
        self.horizontalLayout_17.setMargin(0)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.CircObject3Button = QtGui.QPushButton(self.CircObject3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CircObject3Button.sizePolicy().hasHeightForWidth())
        self.CircObject3Button.setSizePolicy(sizePolicy)
        self.CircObject3Button.setMinimumSize(QtCore.QSize(46, 34))
        self.CircObject3Button.setMaximumSize(QtCore.QSize(46, 34))
        self.CircObject3Button.setText(_fromUtf8(""))
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/object1_v4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CircObject3Button.setIcon(icon21)
        self.CircObject3Button.setIconSize(QtCore.QSize(24, 24))
        self.CircObject3Button.setObjectName(_fromUtf8("CircObject3Button"))
        self.horizontalLayout_17.addWidget(self.CircObject3Button)
        self.CircObjectChooser.addWidget(self.CircObject3)
        self.gridLayout.addWidget(self.CircObjectChooser, 2, 2, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.verticalLayout_4.addWidget(self.ShapeFrame)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_6.addWidget(self.ToolboxFrame)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 940, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setEnabled(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.actionOpen.setIcon(icon)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setEnabled(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionSave.setIcon(icon)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setEnabled(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save"))
        self.actionExport.setIcon(icon)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setEnabled(True)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-open"))
        self.actionImport.setIcon(icon)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionClear = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.actionClear.setIcon(icon)
        self.actionClear.setObjectName(_fromUtf8("actionClear"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("document-save-as"))
        self.actionSave_as.setIcon(icon)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionSet_Position = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("insert-link"))
        self.actionSet_Position.setIcon(icon)
        self.actionSet_Position.setObjectName(_fromUtf8("actionSet_Position"))
        self.actionSet_Image = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("insert-image"))
        self.actionSet_Image.setIcon(icon)
        self.actionSet_Image.setObjectName(_fromUtf8("actionSet_Image"))
        self.actionClear_Position = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.actionClear_Position.setIcon(icon)
        self.actionClear_Position.setObjectName(_fromUtf8("actionClear_Position"))
        self.actionClear_Image = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("edit-clear"))
        self.actionClear_Image.setIcon(icon)
        self.actionClear_Image.setObjectName(_fromUtf8("actionClear_Image"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionClear)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionClear)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionSave_as)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionImport)
        self.toolBar.addAction(self.actionExport)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSet_Position)
        self.toolBar.addAction(self.actionClear_Position)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSet_Image)
        self.toolBar.addAction(self.actionClear_Image)

        self.retranslateUi(MainWindow)
        self.RectTrackChooser.setCurrentIndex(2)
        self.CircTrackChooser.setCurrentIndex(1)
        self.RectFieldChooser.setCurrentIndex(2)
        self.RectObjectChooser.setCurrentIndex(0)
        self.CircFieldChooser.setCurrentIndex(0)
        self.CircObjectChooser.setCurrentIndex(1)
        QtCore.QObject.connect(self.LinearTrackButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_linear_track)
        QtCore.QObject.connect(self.GraphTrackButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_graph_track)
        QtCore.QObject.connect(self.PolygonFieldButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_polygon_field)
        QtCore.QObject.connect(self.PolygonObjectButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_polygon_object)
        QtCore.QObject.connect(self.CircTrack1Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_track1)
        QtCore.QObject.connect(self.CircTrack2Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_track2)
        QtCore.QObject.connect(self.CircTrack3Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_track3)
        QtCore.QObject.connect(self.RectTrack1Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_track1)
        QtCore.QObject.connect(self.RectTrack2Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_track2)
        QtCore.QObject.connect(self.RectTrack3Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_track3)
        QtCore.QObject.connect(self.CircField1Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_field1)
        QtCore.QObject.connect(self.CircField2Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_field2)
        QtCore.QObject.connect(self.CircField3Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_field3)
        QtCore.QObject.connect(self.RectField1Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_field1)
        QtCore.QObject.connect(self.RectField2Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_field2)
        QtCore.QObject.connect(self.RectField3Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_field3)
        QtCore.QObject.connect(self.CircObject1Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_object1)
        QtCore.QObject.connect(self.CircObject2Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_object2)
        QtCore.QObject.connect(self.CircObject3Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_circular_object3)
        QtCore.QObject.connect(self.RectObject1Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_object1)
        QtCore.QObject.connect(self.RectObject2Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_object2)
        QtCore.QObject.connect(self.RectObject3Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.create_rectangular_object3)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.actionAbout, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.show_about_dialog)
        QtCore.QObject.connect(self.AddEnvironment, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.add_environment)
        QtCore.QObject.connect(self.RemoveEnvironment, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.remove_environment)
        QtCore.QObject.connect(self.ShapeTable, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.shape_selection_changed)
        QtCore.QObject.connect(self.ShapeTable, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), MainWindow.shape_edit_request)
        QtCore.QObject.connect(self.RemoveShapes, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.remove_shapes)
        QtCore.QObject.connect(self.EnvironmentList, QtCore.SIGNAL(_fromUtf8("itemSelectionChanged()")), MainWindow.environment_selection_changed)
        QtCore.QObject.connect(self.EnvironmentList, QtCore.SIGNAL(_fromUtf8("itemDoubleClicked(QListWidgetItem*)")), MainWindow.environment_edit_request)
        QtCore.QObject.connect(self.actionClear, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_clear)
        QtCore.QObject.connect(self.actionOpen, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_open)
        QtCore.QObject.connect(self.actionSave_as, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_save_as)
        QtCore.QObject.connect(self.actionSave, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_save)
        QtCore.QObject.connect(self.actionExport, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_export)
        QtCore.QObject.connect(self.actionImport, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_import)
        QtCore.QObject.connect(self.actionSet_Image, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_set_image)
        QtCore.QObject.connect(self.actionSet_Position, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_set_position)
        QtCore.QObject.connect(self.actionClear_Position, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_clear_position)
        QtCore.QObject.connect(self.actionClear_Image, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.action_clear_image)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Amaze", None))
        self.label_4.setText(_translate("MainWindow", "Position source", None))
        self.label_7.setText(_translate("MainWindow", "Environment file", None))
        self.label_6.setText(_translate("MainWindow", "Image source", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Environments", None))
        self.AddEnvironment.setText(_translate("MainWindow", "add new", None))
        self.RemoveEnvironment.setText(_translate("MainWindow", "remove", None))
        self.ShapeFrame.setTitle(_translate("MainWindow", "Shapes", None))
        item = self.ShapeTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "name", None))
        item = self.ShapeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "tags", None))
        self.RemoveShapes.setText(_translate("MainWindow", "remove selected shape", None))
        self.label.setText(_translate("MainWindow", "Tracks", None))
        self.RectTrack1Button.setToolTip(_translate("MainWindow", "Rectangular Track (defined by 3 corners)", None))
        self.RectTrack2Button.setToolTip(_translate("MainWindow", "Rectangular Track (defined by 2 corners)", None))
        self.RectTrack3Button.setToolTip(_translate("MainWindow", "Rectangular Track (defined by center and corner)", None))
        self.LinearTrackButton.setToolTip(_translate("MainWindow", "Simple Polyline or Polygon Track", None))
        self.label_2.setText(_translate("MainWindow", "Objects", None))
        self.label_3.setText(_translate("MainWindow", "Fields", None))
        self.CircTrack1Button.setToolTip(_translate("MainWindow", "Circular Track (defined by 3 corners)", None))
        self.CircTrack2Button.setToolTip(_translate("MainWindow", "Circular Track (defined by 2 corners)", None))
        self.CircTrack3Button.setToolTip(_translate("MainWindow", "Circular Track (defined by center and corner)", None))
        self.GraphTrackButton.setToolTip(_translate("MainWindow", "Graph Track", None))
        self.PolygonFieldButton.setToolTip(_translate("MainWindow", "Polygon Field", None))
        self.PolygonObjectButton.setToolTip(_translate("MainWindow", "Polygon Object", None))
        self.RectField1Button.setToolTip(_translate("MainWindow", "Rectangular Field (defined by 3 corners)", None))
        self.RectField2Button.setToolTip(_translate("MainWindow", "Rectangular Field (defined by 2 corners)", None))
        self.RectField3Button.setToolTip(_translate("MainWindow", "Rectangular Field (defined by center and corner)", None))
        self.RectObject1Button.setToolTip(_translate("MainWindow", "Rectangular Object (defined by 3 corners)", None))
        self.RectObject2Button.setToolTip(_translate("MainWindow", "Rectangular Object (defined by 2 corners)", None))
        self.RectObject3Button.setToolTip(_translate("MainWindow", "Rectangular Object (defined by center and corner)", None))
        self.CircField1Button.setToolTip(_translate("MainWindow", "Circular Field (defined by 3 corners)", None))
        self.CircField2Button.setToolTip(_translate("MainWindow", "Circular Field (defined by 2 corners)", None))
        self.CircField3Button.setToolTip(_translate("MainWindow", "Circular Field (defined by center and corner)", None))
        self.CircObject1Button.setToolTip(_translate("MainWindow", "Circular Object (defined by 3 corners)", None))
        self.CircObject2Button.setToolTip(_translate("MainWindow", "Circular Object (defined by 2 corners)", None))
        self.CircObject3Button.setToolTip(_translate("MainWindow", "Circular Object (defined by center and corner)", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open existing environment file", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave.setToolTip(_translate("MainWindow", "Save environment definition to file", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionExport.setText(_translate("MainWindow", "Export", None))
        self.actionExport.setToolTip(_translate("MainWindow", "Export environment definition to file", None))
        self.actionImport.setText(_translate("MainWindow", "Import", None))
        self.actionImport.setToolTip(_translate("MainWindow", "Import external environment definition", None))
        self.actionClear.setText(_translate("MainWindow", "Clear", None))
        self.actionClear.setToolTip(_translate("MainWindow", "Clear all data", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save as", None))
        self.actionSave_as.setToolTip(_translate("MainWindow", "Save environment definition to different file", None))
        self.actionSet_Position.setText(_translate("MainWindow", "Set Position", None))
        self.actionSet_Position.setToolTip(_translate("MainWindow", "Use new position data", None))
        self.actionSet_Image.setText(_translate("MainWindow", "Set Image", None))
        self.actionSet_Image.setToolTip(_translate("MainWindow", "Use new image data", None))
        self.actionClear_Position.setText(_translate("MainWindow", "Clear Position", None))
        self.actionClear_Position.setToolTip(_translate("MainWindow", "Clear position data", None))
        self.actionClear_Image.setText(_translate("MainWindow", "Clear Image", None))
        self.actionClear_Image.setToolTip(_translate("MainWindow", "Clear image", None))

from fklab.ui.pyqt.graphics import GraphicsCanvas, ScrollStackWidget
import amaze_resources_rc
