# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shape_properties.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ShapeDialog(object):
    def setupUi(self, ShapeDialog):
        ShapeDialog.setObjectName(_fromUtf8("ShapeDialog"))
        ShapeDialog.resize(400, 300)
        self.verticalLayout = QtGui.QVBoxLayout(ShapeDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(ShapeDialog)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.Name = QtGui.QLineEdit(self.frame)
        self.Name.setObjectName(_fromUtf8("Name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.Name)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Tags = QtGui.QPlainTextEdit(self.frame)
        self.Tags.setObjectName(_fromUtf8("Tags"))
        self.verticalLayout_2.addWidget(self.Tags)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tag7 = QtGui.QPushButton(self.frame)
        self.tag7.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag7.setFont(font)
        self.tag7.setText(_fromUtf8(""))
        self.tag7.setCheckable(True)
        self.tag7.setFlat(False)
        self.tag7.setObjectName(_fromUtf8("tag7"))
        self.gridLayout.addWidget(self.tag7, 1, 2, 1, 1)
        self.tag1 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag1.setFont(font)
        self.tag1.setCheckable(True)
        self.tag1.setFlat(False)
        self.tag1.setObjectName(_fromUtf8("tag1"))
        self.gridLayout.addWidget(self.tag1, 0, 0, 1, 1)
        self.tag4 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag4.setFont(font)
        self.tag4.setCheckable(True)
        self.tag4.setFlat(False)
        self.tag4.setObjectName(_fromUtf8("tag4"))
        self.gridLayout.addWidget(self.tag4, 0, 3, 1, 1)
        self.tag5 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag5.setFont(font)
        self.tag5.setCheckable(True)
        self.tag5.setFlat(False)
        self.tag5.setObjectName(_fromUtf8("tag5"))
        self.gridLayout.addWidget(self.tag5, 1, 0, 1, 1)
        self.tag3 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag3.setFont(font)
        self.tag3.setCheckable(True)
        self.tag3.setFlat(False)
        self.tag3.setObjectName(_fromUtf8("tag3"))
        self.gridLayout.addWidget(self.tag3, 0, 2, 1, 1)
        self.tag8 = QtGui.QPushButton(self.frame)
        self.tag8.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag8.setFont(font)
        self.tag8.setText(_fromUtf8(""))
        self.tag8.setCheckable(True)
        self.tag8.setFlat(False)
        self.tag8.setObjectName(_fromUtf8("tag8"))
        self.gridLayout.addWidget(self.tag8, 1, 3, 1, 1)
        self.tag2 = QtGui.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag2.setFont(font)
        self.tag2.setCheckable(True)
        self.tag2.setFlat(False)
        self.tag2.setObjectName(_fromUtf8("tag2"))
        self.gridLayout.addWidget(self.tag2, 0, 1, 1, 1)
        self.tag6 = QtGui.QPushButton(self.frame)
        self.tag6.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(8)
        self.tag6.setFont(font)
        self.tag6.setText(_fromUtf8(""))
        self.tag6.setCheckable(True)
        self.tag6.setFlat(False)
        self.tag6.setObjectName(_fromUtf8("tag6"))
        self.gridLayout.addWidget(self.tag6, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.verticalLayout_2)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.Comments = QtGui.QPlainTextEdit(self.frame)
        self.Comments.setObjectName(_fromUtf8("Comments"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.Comments)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtGui.QDialogButtonBox(ShapeDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ShapeDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), ShapeDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ShapeDialog.reject)
        QtCore.QObject.connect(self.tag1, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag1_clicked)
        QtCore.QObject.connect(self.tag2, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag2_clicked)
        QtCore.QObject.connect(self.tag3, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag3_clicked)
        QtCore.QObject.connect(self.tag4, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag4_clicked)
        QtCore.QObject.connect(self.tag5, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag5_clicked)
        QtCore.QObject.connect(self.tag7, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag7_clicked)
        QtCore.QObject.connect(self.tag6, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag6_clicked)
        QtCore.QObject.connect(self.tag8, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), ShapeDialog.tag8_clicked)
        QtCore.QObject.connect(self.Name, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), ShapeDialog.name_changed)
        QtCore.QObject.connect(self.Tags, QtCore.SIGNAL(_fromUtf8("textChanged()")), ShapeDialog.tags_changed)
        QtCore.QMetaObject.connectSlotsByName(ShapeDialog)

    def retranslateUi(self, ShapeDialog):
        ShapeDialog.setWindowTitle(_translate("ShapeDialog", "Shape Properties", None))
        self.label.setText(_translate("ShapeDialog", "name", None))
        self.label_2.setText(_translate("ShapeDialog", "tags", None))
        self.tag1.setText(_translate("ShapeDialog", "track", None))
        self.tag4.setText(_translate("ShapeDialog", "reward", None))
        self.tag5.setText(_translate("ShapeDialog", "intersection", None))
        self.tag3.setText(_translate("ShapeDialog", "field", None))
        self.tag2.setText(_translate("ShapeDialog", "object", None))
        self.label_3.setText(_translate("ShapeDialog", "comments", None))

